// Tool modules self-register when imported.
import "./deals.js";
import "./persons.js";
import "./organizations.js";
import "./activities.js";
import "./notes.js";
import "./note-comments.js";
import "./pipelines.js";
import "./custom-fields.js";
import "./users.js";
import "./filters.js";
import "./products.js";
import "./projects.js";
import "./project-tasks.js";
import "./files.js";
import "./leads.js";
import "./webhooks.js";
import "./mail.js";
import "./shortcuts.js";
